config/routes.rb
Rails.application.routes.draw do

  root "homes#index"

  get  "logout"     => "sessions#destroy", as: "logout"
  get  "signin"     => "sessions#signin", as: "signin"
  post "app-signin" => "sessions#app_signin", as: "app-signin"
  get  "login"      => "sessions#new", as: "login"
  get  "schedule"   => "homes#schedule", as: "schedule"
  get  "admin"      => "admin#index", as: "admin"

  resources :sessions, path: "auth" do
    collection do
      post :register
    end
  end

  resources :homes
  resources :attachments
  resources :dashboards
  resources :notifications
  resources :log_bids
  resources :settings do
    collection do
      patch :update_profile
      post  :create_address
    end
  end
  resources :auctions do
    collection do
      post "bid" => "auctions#bid", as: "bid"
    end
  end
  resources :transactions do
    collection do
      get   "payment-confirmation"       => "transactions#payment_all", as: "payment-all"
      get   "payment-confirmation/:id"   => "transactions#payment_detail", as: "payment-detail"
      patch "payment-confirmation/:id"   => "transactions#payment_create", as: "payment-create"
      patch "auctioner-confirmation/:id" => "transactions#auctioner_confirmation", as: "auctioner-confirmation"
      post  :send_item
      post  :dispute
      patch "received/:id"        => "transactions#received", as: "received"
      patch "dispute-approve/:id" => "transactions#dispute_approve", as: "dispute-approve"
      patch "dispute-denied/:id"  => "transactions#dispute_denied", as: "dispute-denied"
    end
  end

  namespace :api do
    resources :categories
    resources :brands
    resources :brand_types
    resources :transactions do
      collection do
        get :selling_transaction
      end
    end
    resources :auctions do
      collection do
        get  :by_type
        get  :log
        post :bid
        get  :is_top_bidder
      end
    end
    resources :service do
      collection do
        get  :province
        get  :city
        post :generate_cost
        post :generate_payment_token
        post :payment_transaction_update
      end
    end
    resources :auth do
      collection do
        post :login
        post :register
      end
    end
    resources :users do
      collection do
        get   :personal_information
        patch :update_profile
      end
    end
  end

  namespace :backend, as:"be" do
    resources :dashboard
    resources :categories
    resources :brands
    resources :brand_types
    resources :bid_price_gaps
    resources :personal_informations do
      collection do
        post :verified
      end
    end
    resources :auction_items do
      get    "pictures" => "auction_items#pictures"
      post   "pictures" => "auction_items#create_picture"
      delete "pictures/:id" => "auction_items#delete_picture"
    end
    resources :auctions do
      collection do
        get  :ready
        get  :running
        get  :finished
        post :approve
      end
    end
    resources :transactions do
      collection do
        get   :payment_confirmation
        post  :payment_approve
        patch "delivery-set/:id" => "transactions#delivery_set", as: "delivery-set"
      end
    end
  end
end

app/models/bid_price_gap.rb
class BidPriceGap < ApplicationRecord
	validates :upper_limit, presence: true
	validates :lower_limit, presence: true
	validates :price, presence: true
end

app/controllers/backend/auction_items_controller.rb
class Backend::AuctionItemsController < ApplicationController
	before_action :require_login
  before_action :set_auction_item, only: [:show, :edit, :update, :destroy]

  def index
    @auction_items = AuctionItem.all
  end

  def show
  end

  def new
    @auction_item = AuctionItem.new
    @personal_informations = PersonalInformation.all
    @categories  = Category.all
    @brands 		 = Brand.all
    @brand_types = BrandType.all
  end

  def edit
    @personal_informations = PersonalInformation.all
    @categories  = Category.all
    @brands      = Brand.all
    @brand_types = BrandType.all
  end

  def create
    @auction_item = AuctionItem.create_auction_item(auction_item_params)

    if @auction_item.errors.messages.blank?
      flash[:success] = 'Auction was successfully created.'
      redirect_to be_auction_items_path
    else
      redirect_to new_be_auction_item_path, notice: @auction_item.errors.messages
    end
  end

  def update
    if @auction_item.update(auction_item_params)
      flash[:success] = 'Auction was successfully updated.'
      redirect_to be_auction_items_path
    else
      redirect_to new_be_auction_item_path, notice: @auction_item.errors.messages
    end
  end

  def destroy
    @auction_item.destroy
    flash[:success] = 'Auction was successfully destroyed.'
    redirect_to be_auction_items_path
  end

  def pictures
    @auction_item = AuctionItem.find(params[:auction_item_id])
    @pictures     = Attachment.where(auction_item_id:@auction_item.id)
    @attachment   = @auction_item.attachment.new
  end

  def create_picture
    @auction_item = AuctionItem.find(params[:auction_item_id])
    @attachment = @auction_item.attachment.new(attachment_params)
    if @attachment.save
      redirect_to be_auction_item_pictures_path(@auction_item), notice:{
      	:success => 'Picture was successfully added.'
      }
    else
      redirect_to be_auction_item_pictures_path(@auction_item), notice: @attachment.errors.messages
    end
  end

  def delete_picture
    @auction_item = AuctionItem.find(params[:auction_item_id])
    @attachment = Attachment.find(params[:id])
    @attachment.destroy
    redirect_to be_auction_item_pictures_path, notice: {
    	:success => 'Picture was successfully removed.'
    }
  end

  private
  def set_auction_item
    @auction_item = AuctionItem.find(params[:id])
  end

  def auction_item_params
    params.require(:auction_item).permit(:name, :price, :description, :min_description, :plus_description, :condition, :user_id, :category_id, :brand_id, :brand_type_id, :production_date, :tag, :weight, :volume)
  end

  def attachment_params
    params.require(:attachment).permit(:name, :file_type)
  end
end

app/controllers/backend/auctions_controller.rb
class Backend::AuctionsController < ApplicationController
	before_action :set_auction, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:bid]
  skip_before_action :verify_authenticity_token, only: [:bid, :create_with_item]

  def index
    @auctions = Auction.all
  end

  def show
  end

  def new
    @auction = Auction.new
    @item_used = Auction.all.select(:auction_item_id)
    @auction_items = AuctionItem.where.not(id: @item_used)
  end

  def edit
    @auction_items = AuctionItem.all
  end

  def create
    @auction = Auction.new(auction_params)

    if @auction.save
      flash[:success] = 'Auction was successfully created.'
      redirect_to be_auctions_path
    else
      redirect_to new_be_auction_path, notice: @auction.errors.messages
    end
  end

  def update
    if @auction.update(auction_params)
      flash[:success] = 'Auction was successfully updated.'
      redirect_to be_auctions_path
    else
      redirect_to new_be_auction_path, notice: @auction.errors.messages
    end
  end

  def destroy
    @auction.destroy
    flash[:success] = 'Auction was successfully destroyed.'
    redirect_to be_auctions_path
  end

  def approve
    auction = Auction.find(params[:auction_id])
    interval =  auction.interval.to_i
    auction.end_date = auction.start_date + interval.day
    auction.price_bid = 10000
    auction.auction_status = "Approved"
    auction.auction_type = "general"
    auction.join_fee = 0
    if auction.save
      Auction.delay(run_at: auction.end_date).generate_winner(auction.id)
      flash[:success] = 'Auction was successfully approved.'
      auction_item = AuctionItem.find(auction.auction_item_id)
      auction_item.is_approve = true
      auction_item.save
    else
      flash[:danger] = 'Auction was failed approved.'
    end

    redirect_to be_auctions_path
  end

  def ready
    @auctions = Auction.where("auction_status = 'Approved'")
  end

  def running
    @auctions = Auction.where("auction_status = 'Running'")
  end

  def finished
    @auctions = Auction.where("auction_status = 'Finished'")
  end

  private
  def set_auction
    @auction = Auction.find(params[:id])
  end

  def auction_params
    params.require(:auction).permit(:auction_item_id, :start_price, :start_date, :interval)
  end
end

app/controllers/backend/bid_price_gaps_controller.rb
class Backend::BidPriceGapsController < ApplicationController
	before_action :set_bid_price_gap, only: [:show, :edit, :update, :destroy]

  def index
    @bid_price_gaps = BidPriceGap.all
    @bid_price_gap  = BidPriceGap.new
  end

  def show
  end

  def new
    @bid_price_gaps = BidPriceGap.all
    @bid_price_gap  = BidPriceGap.new
    render 'index'
  end

  def edit
    @bid_price_gaps = BidPriceGap.all
    render 'index'
  end

  def create
    @bid_price_gap = BidPriceGap.new(bid_price_gap_params)

    if @bid_price_gap.save
      redirect_to be_bid_price_gaps_path, notice: {
      	:success => 'Category was successfully created.'
      }
    else
      redirect_to be_bid_price_gaps_path, notice: {
      	:danger => @bid_price_gap.errors.messages
      }
    end
  end

  def update
    if @bid_price_gap.update(bid_price_gap_params)
      redirect_to be_bid_price_gaps_path, notice: {
      	:success => 'Category was successfully created.'
      }
    else
      redirect_to be_bid_price_gaps_path, notice: {
      	:danger => @bid_price_gap.errors.messages
      }
    end
  end

  def destroy
    @bid_price_gap.destroy
    redirect_to be_bid_price_gaps_path, notice: {
    	:success => 'Category was successfully destroyed.'
    }
  end

  private
    def set_bid_price_gap
      @bid_price_gap = BidPriceGap.find(params[:id])
    end

    def bid_price_gap_params
      params.require(:bid_price_gap).permit(:upper_limit, :lower_limit, :price)
    end
end

app/controllers/backend/brand_types_controller.rb
class Backend::BrandTypesController < ApplicationController
	before_action :set_brand_type, only: [:show, :edit, :update, :destroy]

  def index
    @brand_types = BrandType.all
    @brands 		 = Brand.all
    @brand_type  = BrandType.new
  end

  def show
  end

  def new
    @brand_types = BrandType.all
    @brands 	   = Brand.all
    @brand_type  = BrandType.new
    render 'index'
  end

  def edit
    @brand_types = BrandType.all
    @brands 		 = Brand.all
    render 'index'
  end

  def create
    @brand_type = BrandType.new(brand_type_params)

    if @brand_type.save
      redirect_to be_brand_types_path, notice: {
      	:success => 'Brand type was successfully created.'
      }
    else
      redirect_to be_brand_types_path, notice: {
      	:danger => @brand_type.errors.messages
      }
    end
  end

  def update
    if @brand_type.update(brand_type_params)
      redirect_to be_brand_types_path, notice: {
      	:success => 'Brand type was successfully updated.'
      }
    else
      redirect_to be_brand_types_path, notice: {
      	:danger => @brand_type.errors.messages
      }
    end
  end

  def destroy
    @brand_type.destroy
    redirect_to be_brand_types_path, notice: {
    	:success => 'Brand type was successfully destroyed.'
    }
  end

  private
  def set_brand_type
    @brand_type = BrandType.find(params[:id])
  end

 	def brand_type_params
    params.require(:brand_type).permit(:name, :tags, :brand_id)
  end
end

app/controllers/backend/brands_controller.rb
class Backend::BrandsController < ApplicationController
	before_action :set_brand, only: [:show, :edit, :update, :destroy]

  def index
    @brands 		= Brand.all
    @categories = Category.all
    @brand 			= Brand.new
  end

  def show
  end

  def new
    @brands 		= Brand.all
    @categories = Category.all
    @brand 			= Brand.new
    render 'index'
  end

  def edit
    @brands 		= Brand.all
    @categories = Category.all
    render 'index'
  end

  def create
    @brand = Brand.new(brand_params)

    if @brand.save
      redirect_to be_brands_path, notice:{
      	:success => 'Brand was successfully created.'
      }
    else
      redirect_to be_brands_path, notice: {
      	:danger => @brand.errors.messages
      }
    end
  end

  def update
    if @brand.update(brand_params)
      redirect_to be_brands_path, notice:{
      	:success => 'Brand was successfully updated.'
      }
    else
      redirect_to be_brands_path, notice: {
      	:danger => @brand.errors.messages
      }
    end
  end

  def destroy
    @brand.destroy
    redirect_to be_brands_path, notice:{
    	:success => 'Brand was successfully destroyed.'
    }
  end

  private
  def set_brand
    @brand = Brand.find(params[:id])
  end

  def brand_params
    params.require(:brand).permit(:name, :tags, :category_id)
  end
end

app/controllers/backend/categories_controller.rb
class Backend::CategoriesController < ApplicationController
  before_action :require_admin_login
	before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
    @category   = Category.new
  end

  def show
  end

  def new
    @categories = Category.all
    @category   = Category.new
    render 'index'
  end

  def edit
    @categories = Category.all
    render 'index'
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to be_categories_path, notice: {
        :success => 'Category was successfully created.'
      }
    else
      redirect_to be_categories_path, notice: {
        :danger => @category.errors.messages
      }
    end
  end

  def update
    if @category.update(category_params)
        redirect_to be_categories_path, notice: {
          :success => 'Category was successfully updated.'
        }
    else
      redirect_to be_categories_path, notice: {
        :danger => @category.errors.messages
      }
    end
  end

  def destroy
    @category.destroy
    redirect_to be_categories_path, notice: {
      :success => 'Category was successfully destroyed.'
    }
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :tags)
  end
end

app/controllers/backend/dashboard_controller.rb
class Backend::DashboardController < ApplicationController
	def index
		@pi = PersonalInformation.all
		@auction = Auction.all.order(created_at: :desc)
		@auction_running = Auction.where("auction_status = 'Approved'").order(created_at: :desc)
		@pi_verified = PersonalInformation.where(verification_status: true).count
		@pi_unverified = PersonalInformation.where(verification_status: false).count
		@auction_request = Auction.where(auction_status: 'New').count
		@auction_ongoing = Auction.where(auction_status: 'Approved').count
		@auction_finished = Auction.where(auction_status: 'Finishied').count
	end
end

app/controllers/backend/personal_informations_controller.rb
class Backend::PersonalInformationsController < ApplicationController
	before_action :set_personal_information, only: [:show, :edit, :update, :destroy]

  def index
    @personal_informations = PersonalInformation.all
  end

  def show
  end

  def new
    @personal_information = PersonalInformation.new
  end

  def edit
  end

  def create
    @personal_information = PersonalInformation.create_personal_information(personal_information_params)

    if @personal_information.errors.messages.blank?
      flash[:success] = 'User was successfully created.'
      redirect_to be_personal_informations_path
    else
    	redirect_to new_be_personal_information_path,  notice: @personal_information.errors.messages
    end
  end

  def update
    if @personal_information.update(personal_information_params)
      flash[:success] = 'User was successfully updated.'
      redirect_to be_personal_informations_path
    else
    	redirect_to new_be_personal_information_path,  notice: @personal_information.errors.messages
    end
  end

  def verified
    pi = PersonalInformation.find(params[:id])
    pi.verification_status = true
    if pi.save
      flash[:success] = 'User was successfully Verified.'
    else
      flash[:danger] = 'User was failed Verified.'
    end
    redirect_to be_personal_informations_path
  end

  def destroy
    @personal_information.destroy
    flash[:success] = 'User was successfully destroyed.'
    redirect_to be_personal_informations_path
  end

  private
  def set_personal_information
    @personal_information = PersonalInformation.find(params[:id])
  end

  def personal_information_params
    params.permit(:first_name, :last_name, :gender, :birth_place, :birth_date, :address, :phone_number, :telephone, :profile_picture, :username, :password, :email, :user_id)
  end
end

app/helpers/backend/auction_items_helper.rb
module Backend::AuctionItemsHelper
end

app/helpers/backend/auctions_helper.rb
module Backend::AuctionsHelper
end

app/helpers/backend/bid_price_gaps_helper.rb
module Backend::BidPriceGapsHelper
end

app/helpers/backend/brand_types_helper.rb
module Backend::BrandTypesHelper
end

app/helpers/backend/brands_helper.rb
module Backend::BrandsHelper
end

app/helpers/backend/categories_helper.rb
module Backend::CategoriesHelper
end

app/helpers/backend/dashboard_helper.rb
module Backend::DashboardHelper
end

app/helpers/backend/personal_informations_helper.rb
module Backend::PersonalInformationsHelper
end

app/helpers/backend/transactions_helper.rb
module Backend::TransactionsHelper
end

app/helpers/bid_price_gaps_helper.rb
module BidPriceGapsHelper
end

app/views/backend/bid_price_gaps/index.html.erb
<div class="animated fadeIn">
  <div class="card">
    <div class="card-header">
      <i class="fa fa-edit"></i> Bid Price Management
      <div class="card-actions">
        <%= link_to raw('<i class="fa fa-plus"></i>'),
                new_be_bid_price_gap_path,
                data: {toggle: 'tooltip'},
                :class => 'btn btn-success pull-right btn-sm',
                :title => 'Buat User Baru' %>
      </div>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-md-8 col-xs-12">
          <table class="table table-striped table-bordered datatable">
            <thead>
              <tr>
                <th>Upper limit</th>
                <th>Lower limit</th>
                <th>Price</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              <% @bid_price_gaps.each do |bid_price_gap| %>
                <tr>
                  <td><%= bid_price_gap.upper_limit %></td>
                  <td><%= bid_price_gap.lower_limit %></td>
                  <td><%= bid_price_gap.price %></td>
                  <td>
                    <%= link_to raw('<i class="fa fa-edit"></i>'),
                                   edit_be_bid_price_gap_path(bid_price_gap),
                                  data: {toggle: 'tooltip'},
                                  :class => 'btn btn-info',
                                  :title => 'Edit' %>
                    <%= link_to raw('<i class="fa fa-trash-o"></i>'),
                                  be_bid_price_gap_path(bid_price_gap),
                                  method: :delete,
                                  data: {confirm: 'Are you sure?', toggle: 'tooltip' },
                                  :class => 'btn btn-danger',
                                  :title => 'Delete' %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="col-md-4 col-xs-12">
          <% if flash[:notice].present? %>
            <% flash[:notice].each do |key, value| %>
              <div class="alert alert-<%= key %> alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <% if value[1].nil? %>
                  <% value.each do |field, res| %>
                    <%= field+" "+res[0] %></br>
                  <% end %>
                <% else %>
                <%= value %></br>
                <% end %>
              </div>
            <% end %>
          <% end %>
          <%= form_for ["be", @bid_price_gap], local: true, :class=>"form-horizontal" do |f| %>
            <div class="form-group row">
              <label class="col-md-3 col-form-label" for="upper_limit">
                <strong><%= f.label 'Upper Limit' %> : </strong>
              </label>
              <div class="col-md-9">
                <%= f.text_field :upper_limit, {:class => 'form-control', :placeholder => 'Name', :autocomplete => 'off'} %>
              </div>
            </div>
            <div class="form-group row">
              <label class="col-md-3 col-form-label" for="lower_limit">
                <strong><%= f.label 'Lower Limit' %> : </strong>
              </label>
              <div class="col-md-9">
                <%= f.text_field :lower_limit, {:class => 'form-control', :placeholder => 'Name', :autocomplete => 'off'} %>
              </div>
            </div>
            <div class="form-group row">
              <label class="col-md-3 col-form-label" for="price">
                <strong><%= f.label 'Price' %> : </strong>
              </label>
              <div class="col-md-9">
                <%= f.text_field :price, {:class => 'form-control', :placeholder => 'Price', :autocomplete => 'off'} %>
              </div>
            </div>
            <div class="form-group row">
              <div class="col-md-9 offset-md-3">
                <%= f.submit({:class => 'btn btn-primary'}) %>
                <%= f.button("Reset",{:class => 'btn btn-warning', :type => 'reset'}) %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :page_scripts do %>
  <script>
    $(function(){
      $('.datatable').DataTable();
      $('.datatable').attr('style', 'border-collapse: collapse !important');
    });
  </script>
<% end %>

app/views/backend/bid_price_gaps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Upper limit:</strong>
  <%= @bid_price_gap.upper_limit %>
</p>

<p>
  <strong>Lower limit:</strong>
  <%= @bid_price_gap.lower_limit %>
</p>

<p>
  <strong>Price:</strong>
  <%= @bid_price_gap.price %>
</p>

<%= link_to 'Edit', edit_bid_price_gap_path(@bid_price_gap) %> |
<%= link_to 'Back', bid_price_gaps_path %>