config/routes.rb
Rails.application.routes.draw do

  root "homes#index"

  get  "logout"     => "sessions#destroy", as: "logout"
  get  "signin"     => "sessions#signin", as: "signin"
  post "app-signin" => "sessions#app_signin", as: "app-signin"
  get  "login"      => "sessions#new", as: "login"
  get  "schedule"   => "homes#schedule", as: "schedule"
  get  "admin"      => "admin#index", as: "admin"

  resources :sessions, path: "auth" do
    collection do
      post :register
    end
  end

  resources :homes
  resources :attachments
  resources :dashboards
  resources :notifications
  resources :log_bids
  resources :settings do
    collection do
      patch :update_profile
      post  :create_address
    end
  end
  resources :auctions do
    collection do
      post "bid" => "auctions#bid", as: "bid"
    end
  end
  resources :transactions do
    collection do
      get   "payment-confirmation"       => "transactions#payment_all", as: "payment-all"
      get   "payment-confirmation/:id"   => "transactions#payment_detail", as: "payment-detail"
      patch "payment-confirmation/:id"   => "transactions#payment_create", as: "payment-create"
      patch "auctioner-confirmation/:id" => "transactions#auctioner_confirmation", as: "auctioner-confirmation"
      post  :send_item
      post  :dispute
      patch "received/:id"        => "transactions#received", as: "received"
      patch "dispute-approve/:id" => "transactions#dispute_approve", as: "dispute-approve"
      patch "dispute-denied/:id"  => "transactions#dispute_denied", as: "dispute-denied"
    end
  end

  namespace :api do
    resources :categories
    resources :brands
    resources :brand_types
    resources :transactions do
      collection do
        get :selling_transaction
      end
    end
    resources :auctions do
      collection do
        get  :by_type
        get  :log
        post :bid
        get  :is_top_bidder
      end
    end
    resources :service do
      collection do
        get  :province
        get  :city
        post :generate_cost
        post :generate_payment_token
        post :payment_transaction_update
      end
    end
    resources :auth do
      collection do
        post :login
        post :register
      end
    end
    resources :users do
      collection do
        get   :personal_information
        patch :update_profile
      end
    end
  end

  namespace :backend, as:"be" do
    resources :dashboard
    resources :categories
    resources :brands
    resources :brand_types
    resources :bid_price_gaps
    resources :personal_informations do
      collection do
        post :verified
      end
    end
    resources :auction_items do
      get    "pictures" => "auction_items#pictures"
      post   "pictures" => "auction_items#create_picture"
      delete "pictures/:id" => "auction_items#delete_picture"
    end
    resources :auctions do
      collection do
        get  :ready
        get  :running
        get  :finished
        post :approve
      end
    end
    resources :transactions do
      collection do
        get   :payment_confirmation
        post  :payment_approve
        patch "delivery-set/:id" => "transactions#delivery_set", as: "delivery-set"
      end
    end
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
	belongs_to :user
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:name, :message, :type, :user_id, :is_read)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_with(model: notification, local: true) do |form| %>
  <% if notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :is_read %>
    <%= form.check_box :is_read %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notifications</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Message</th>
      <th>Type</th>
      <th>User</th>
      <th>Is read</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.name %></td>
        <td><%= notification.message %></td>
        <td><%= notification.type %></td>
        <td><%= notification.user_id %></td>
        <td><%= notification.is_read %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @notification.name %>
</p>

<p>
  <strong>Message:</strong>
  <%= @notification.message %>
</p>

<p>
  <strong>Type:</strong>
  <%= @notification.type %>
</p>

<p>
  <strong>User:</strong>
  <%= @notification.user_id %>
</p>

<p>
  <strong>Is read:</strong>
  <%= @notification.is_read %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>