config/routes.rb
Rails.application.routes.draw do

  root "homes#index"

  get  "logout"     => "sessions#destroy", as: "logout"
  get  "signin"     => "sessions#signin", as: "signin"
  post "app-signin" => "sessions#app_signin", as: "app-signin"
  get  "login"      => "sessions#new", as: "login"
  get  "schedule"   => "homes#schedule", as: "schedule"
  get  "admin"      => "admin#index", as: "admin"

  resources :sessions, path: "auth" do
    collection do
      post :register
    end
  end

  resources :homes
  resources :attachments
  resources :dashboards
  resources :notifications
  resources :log_bids
  resources :settings do
    collection do
      patch :update_profile
      post  :create_address
    end
  end
  resources :auctions do
    collection do
      post "bid" => "auctions#bid", as: "bid"
    end
  end
  resources :transactions do
    collection do
      get   "payment-confirmation"       => "transactions#payment_all", as: "payment-all"
      get   "payment-confirmation/:id"   => "transactions#payment_detail", as: "payment-detail"
      patch "payment-confirmation/:id"   => "transactions#payment_create", as: "payment-create"
      patch "auctioner-confirmation/:id" => "transactions#auctioner_confirmation", as: "auctioner-confirmation"
      post  :send_item
      post  :dispute
      patch "received/:id"        => "transactions#received", as: "received"
      patch "dispute-approve/:id" => "transactions#dispute_approve", as: "dispute-approve"
      patch "dispute-denied/:id"  => "transactions#dispute_denied", as: "dispute-denied"
    end
  end

  namespace :api do
    resources :categories
    resources :brands
    resources :brand_types
    resources :transactions do
      collection do
        get :selling_transaction
      end
    end
    resources :auctions do
      collection do
        get  :by_type
        get  :log
        post :bid
        get  :is_top_bidder
      end
    end
    resources :service do
      collection do
        get  :province
        get  :city
        post :generate_cost
        post :generate_payment_token
        post :payment_transaction_update
      end
    end
    resources :auth do
      collection do
        post :login
        post :register
      end
    end
    resources :users do
      collection do
        get   :personal_information
        patch :update_profile
      end
    end
  end

  namespace :backend, as:"be" do
    resources :dashboard
    resources :categories
    resources :brands
    resources :brand_types
    resources :bid_price_gaps
    resources :personal_informations do
      collection do
        post :verified
      end
    end
    resources :auction_items do
      get    "pictures" => "auction_items#pictures"
      post   "pictures" => "auction_items#create_picture"
      delete "pictures/:id" => "auction_items#delete_picture"
    end
    resources :auctions do
      collection do
        get  :ready
        get  :running
        get  :finished
        post :approve
      end
    end
    resources :transactions do
      collection do
        get   :payment_confirmation
        post  :payment_approve
        patch "delivery-set/:id" => "transactions#delivery_set", as: "delivery-set"
      end
    end
  end
end

app/controllers/api/transactions_controller.rb
class Api::TransactionsController < ApplicationController
	before_action :set_transaction, only: [:show]
	def index
		user_id = params[:user_id]
		@transactions = Transaction.where(user_id: user_id)

		respond_to do |format|
      if @transactions
        format.json { render :index, status: 200, message: "Get Transaction" }
      else
      	format.json { render :index, status: 400, message: "Transaction no found" }
      end
    end
	end

	def selling_transaction
		user_id = params[:user_id]
		@transactions = Transaction.where(auctioner_id: user_id)

		respond_to do |format|
      if @transactions
        format.json { render :index, status: 200, message: "Get Transaction" }
      else
      	format.json { render :index, status: 400, message: "Transaction no found" }
      end
    end
	end

	def show
		respond_to do |format|
      if @transaction
        format.json { render :show, status: 200, message: "Get Transaction" }
      else
      	format.json { render :show, status: 400, message: "Transaction no found" }
      end
    end
	end

	private
  def set_transaction
    @transaction = Transaction.where(id: params[:id]).first
  end
end

app/controllers/backend/transactions_controller.rb
class Backend::TransactionsController < ApplicationController
	before_action :set_transacation, only: [:show, :payment_approve, :delivery_set]

	def index
		@transactions = Transaction.all
	end

	def payment_confirmation
		@transactions = Transaction.where(status: "02")
	end

	def payment_approve
		@transaction.status = "03"
		if @transaction.save
			flash[:success] = 'Payment has approved successfully.'
      redirect_to be_transactions_path
    else
    	redirect_to be_transactions_path,  notice: @transaction.errors.messages
    end
	end

	def delivery_set
		@transaction.status = "06"
		if @transaction.save
			flash[:success] = 'Transaction has set as delivered.'
      redirect_to be_transactions_path
    else
    	redirect_to be_transactions_path,  notice: @transaction.errors.messages
    end
	end

	private

	def set_transacation
    @transaction = Transaction.find(params[:id])
  end

  def approve_param
    params.permit(:first_name, :last_name, :gender, :birth_place, :birth_date, :address, :phone_number, :telephone, :profile_picture, :username, :password, :email, :user_id)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy, :send_item, :dispute]
  before_action :set_personal_information, only: [:index, :show, :payment_all, :payment_detail]
  skip_before_action :verify_authenticity_token, only: [:send_item]

  # GET /transactions
  # GET /transactions.json
  def index
    user_id = session[:user_id]
    @user   = User.find(user_id)
    @transactions      = Transaction.where(user_id: user_id)
    @transactions_self  = Transaction.where(auctioner_id: user_id)
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @pa = PersonalInformation.where(user_id: session[:user_id]).first
    render :layout => false
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def payment_all
    user_id = session[:user_id]
    @transactions = Transaction.where(user_id: user_id).where(status: "01")
  end

  def payment_detail
    user_id = session[:user_id]
    @transaction = Transaction.where(trx_no: params[:id]).first
  end

  def payment_create
    user_id = session[:user_id]
    @transaction = Transaction.where(trx_no: params[:id]).first
    @transaction.status = "02"
    @transaction.save
    flash[:success] = 'Terimakasih telah melakukan pembayaran, akan di konfirmasi paling lambat 1x24 jam'
    redirect_to transactions_path
  end

  def auctioner_confirmation
    user_id = session[:user_id]
    @transaction = Transaction.where(trx_no: params[:id]).first
    @transaction.status = "04"
    @transaction.save
    flash[:success] = 'Transaksi telah di konfirmasi, segera lakukan pengiriman barang'
    redirect_to transactions_path
  end

  def send_item
    @transaction.resi_no = params[:resi_no]
    @transaction.resi_no_image = params[:resi_no_image]
    @transaction.status = "05"
    @transaction.save
    flash[:success] = 'Terimakasih telah melakukan pengiriman barang'
    redirect_to transactions_path
  end

  def received
    user_id = session[:user_id]
    @transaction = Transaction.where(trx_no: params[:id]).first
    @transaction.status = "08"
    @transaction.save
    flash[:success] = 'Terimakaih atas konfirmasi anda, ikuti lelang lainnya.'
    redirect_to transactions_path
  end

  def dispute
    @transaction.status = "07"
    @transaction.save
    flash[:success] = 'Pegajuan pengemabalian barang anda akan segera di proses, terimakash.'
    redirect_to transactions_path
  end

  def dispute_approve
    @transaction.status = "07.a"
    @transaction.save
    flash[:success] = 'Pengembalian barang telah diterima, barang akan segera di kembalikan oleh pemenang'
    redirect_to transactions_path
  end

  def dispute_denied
    @transaction.status = "07.b"
    @transaction.save
    flash[:success] = 'Pengembalian barang ditolak, peganjuan ini akan segera di verifikasi oleh pihak kami'
    redirect_to transactions_path
  end

  private
  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  def set_personal_information
    user_id = session[:user_id]
    @pa = PersonalInformation.where(user_id: user_id).first
  end

  def transaction_params
    params.require(:transaction).permit(:trx_no, :auction_id, :trx_date, :due_date, :status, :price, :unique_number, :user_id, :resi_no, :address_id)
  end
end

app/helpers/api/transactions_helper.rb
module Api::TransactionsHelper
end

app/helpers/backend/transactions_helper.rb
module Backend::TransactionsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :trx_no %>
    <%= form.text_field :trx_no %>
  </div>

  <div class="field">
    <%= form.label :auction_id %>
    <%= form.number_field :auction_id %>
  </div>

  <div class="field">
    <%= form.label :trx_date %>
    <%= form.datetime_select :trx_date %>
  </div>

  <div class="field">
    <%= form.label :due_date %>
    <%= form.datetime_select :due_date %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :unique_number %>
    <%= form.number_field :unique_number %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :resi_no %>
    <%= form.text_field :resi_no %>
  </div>

  <div class="field">
    <%= form.label :address_id %>
    <%= form.number_field :address_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/payment_all.html.erb
<div class="container" style="margin-top: 80px;padding: 0px;margin-bottom: 120px">
  <div class="row">
    <div class="col-12">
      <nav class="breadcrumb">
        <a class="breadcrumb-item" href="#">Home</a>
        <span class="breadcrumb-item active">
          Konfirmasi Pembayaran
        </span>
      </nav>
    </div>
  </div>
	<div class="row">
		<div class="col-12 col-md-3">
			<%= render 'partial/user/components/sidebar' %>
		</div>
    <div class="col-12 col-md-9">
      <div class="row">
        <div class="col-12">
          <ul class="nav nav-tabs" role="tablist">
            <li class="nav-item">
              <a class="nav-link active" data-toggle="tab" href="#home4" role="tab" aria-controls="home"><i class="icon-calculator"></i> Konfirmasi Pembayaran &nbsp;<span class="badge badge-pill badge-success"><%= @pa.user.auction_user.count %></span></a>
            </li>
          </ul>
          <div class="tab-content" style="min-height: 450px">
            <div class="tab-pane active" id="home4" role="tabpanel">
              <% if @transactions.count==0 %>
              <div class="alert alert-info alert-dismissible fade show" role="alert">
                <strong>Tidak ada data transaksi ditemukan!</strong> Mulai lelang anda segera.
              </div>
              <% end %>

              <% @transactions.each do |item|%>
                <div class="row">
                  <div class="col-12">
                    <div class="card">
                      <div class="card-header" style="background-color: #fff">
                        <div class="float-left">
                          <strong><%= item.auction.auction_item.name %></strong> (<%= item.auction.auction_item.condition %>)
                        </div>
                        <div class="float-right" style="font-size: 18px">
                          <span>Rp</span>
                          <strong><span style="color:#20A8D8"><%= item.price %></span></strong>
                        </div>
                      </div>
                      <div class="card-body">
                        <div class="row">
                          <div class="col-3">
                            <div style="background-image: url('<%= item.auction.auction_item.attachment.first.name %>');width: 100%;height: 140px;background-size: auto 100%">
                            </div>
                          </div>
                          <div class="col-9">
                            <ul class="list-group">
                              <li class="list-group-item">
                                <span class="fa fa-users"></span>&nbsp;Bidder : <span class="bidder_count">
                                  <%= item.trx_no %>
                                </span>
                              </li>
                              <li class="list-group-item">
                                <span class="fa fa-calendar"></span>&nbsp;Trx Date : <%= item.trx_date %>
                              </li>
                              <li class="list-group-item">
                                <span class="fa fa-legal"></span>&nbsp;Due Date : Rp <%= item.due_date %>
                              </li>
                            </ul>
                          </div>
                        </div>
                      </div>
                      <div class="card-footer">
                        <div class="icon-bar float-left" style="margin-top: 6px;font-size: 17px">
                          <span>Total Rp</span>
                          <strong><span style="color:#20A8D8"><%= item.price %></span></strong>
                        </div>
                        <a href="<%= payment_detail_transactions_path(item.trx_no) %>" class="btn btn-primary float-right">
                          <span class="fa fa-credit-card"></span>
                          Bayar
                        </a>
                        <a href="<%= auction_path(item.auction) %>" target="_blank" class="btn btn-success float-right" style="margin-right: 5px;">
                          <span class="fa fa-eye"></span>
                          Detail
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
	</div>
</div>

<% content_for :customjs do %>
<% end %>

app/views/transactions/payment_detail.html.erb
<div class="container" style="margin-top: 80px;padding: 0px;margin-bottom: 120px">
  <div class="row">
    <div class="col-12">
      <nav class="breadcrumb">
        <a class="breadcrumb-item" href="#">Home</a>
        <span class="breadcrumb-item active">
          Konfirmasi Pembayaran
        </span>
      </nav>
    </div>
  </div>
	<div class="row">
		<div class="col-12 col-md-3">
			<%= render 'partial/user/components/sidebar' %>
		</div>
    <div class="col-12 col-md-9">
      <div class="card" style="min-height: 400px;padding: 30px 0px">
        <div class="card-body text-center">
          <div class="row">
            <div class="col-12">
              <h3>Batas Waktu Pembayaran</h3>
              <h4  style="color: #018AFC">
                <span id="clockdiv">0D : 0H : 0M : 0S</span>
              </h4>
            </div>
            <div class="col-12" style="margin-top: 20px">
              <div class="card">
                <div class="card-header" style="background-color: #fff">
                  <div class="float-left">
                    <strong><%= @transaction.auction.auction_item.name %></strong> (<%= @transaction.auction.auction_item.condition %>)
                  </div>
                  <div class="float-right" style="font-size: 18px">
                    <span>Total Rp</span>
                    <strong><span style="color:#20A8D8"><%= @transaction.price %></span></strong>
                  </div>
                </div>
                <div class="card-body">
                  <div class="row">
                    <div class="col-3">
                      <div style="background-image: url('<%= @transaction.auction.auction_item.attachment.first.name %>');width: 100%;height: 140px;background-size: auto 100%">
                      </div>
                    </div>
                    <div class="col-9 text-left">
                      <ul class="list-group">
                        <li class="list-group-item">
                          <span class="fa fa-users"></span>&nbsp;Bidder : <span class="bidder_count">
                            <%= @transaction.trx_no %>
                          </span>
                        </li>
                        <li class="list-group-item">
                          <span class="fa fa-calendar"></span>&nbsp;Trx Date : <%= @transaction.trx_date %>
                        </li>
                        <li class="list-group-item">
                          <span class="fa fa-legal"></span>&nbsp;Due Date : Rp <%= @transaction.due_date %>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="card-footer">
                  <a href="<%= auction_path(@transaction.auction_id) %>" target="_blank" class="btn btn-success float-right" style="margin-right: 5px;">
                    <span class="fa fa-eye"></span>
                    Detail
                  </a>
                </div>
              </div>
            </div>

            <div class="col-12 col-md-7 text-left" style="margin-top: 20px;padding-top: 20px">
              <div style="border-bottom: solid 1px #018AFC;margin-bottom: 10px">
                <strong>Alamat pengiriman</strong>
              </div> 
              <div>
                <strong><%= @pa.first_name+" "+@pa.last_name %></strong><br>
                <%= @pa.phone_number %><br>
                <%= @pa.address %>
              </div>
              <div style="border-top: solid 1px #018AFC;margin-bottom: 10px;padding-top: 5px">
                <a href="#" class="btn btn-primary float-right">Pilih alamat lain</a>
              </div>

              <div style="border-bottom: solid 1px #018AFC;margin-bottom: 10px;margin-top: 50px">
                <strong>Metode Pengiriman</strong>
              </div>
              <div class="form-group row" style="padding-right: 15px">
                <label class="col-4" style="margin-top: 7px"><strong>Kurir pilihan</strong></label>
                <select name="courier" class="form-control col-8 select2" id="courier">
                  <option value="jne">JNE</option>
                  <option value="pos">POS Indonesia</option>
                  <option value="tiki">TIKI</option>
                </select>
              </div>
              <div class="form-group row" style="padding-right: 15px">
                <label class="col-4" style="margin-top: 7px"><strong>Durasi</strong></label>
                <select name="" class="form-control col-8 select2" id="duration">
                </select>
              </div>
              <div class="form-group row" id="courier-selected" style="padding-right: 15px">
                <label class="col-4">&nbsp;</label>
                <div class="col-8" id="pre-cost" style="padding-left: 0px">
                  (Pilih durasi pengiriman)
                </div>
              </div>
            </div>

            <div class="col-12 col-md-5 text-left" style="margin-top: 20px">
              <div class="card">
                <div class="card-body">
                  <div style="border-bottom: solid 1px #018AFC;margin-bottom: 10px">
                    <strong>Ringkasan Transaksi</strong>
                  </div>
                  <div class="row">
                    <div class="col-12" style="padding-bottom: 5px;margin-top: 5px">
                      <div class="float-left">
                        Total Harga
                      </div>
                      <div class="float-right">
                        Rp <%= @transaction.price %>
                      </div>
                    </div>
                    <div class="col-12" style="padding-bottom: 5px">
                      <div class="float-left">
                        Ongkos Kirim
                      </div>
                      <div class="float-right">
                        <span id="delivery-cost-label">-</span>
                      </div>
                    </div>
                    <div class="col-12" style="padding-bottom: 5px">
                      <div class="float-left">
                        Asusransi Pengiriman
                      </div>
                      <div class="float-right">
                        Rp 0
                      </div>
                    </div>
                  </div>
                  <div style="border-bottom: solid 1px #018AFC;border-top: solid 1px #018AFC;margin-bottom: 10px;padding:10px 0px;margin:10px 0px">
                    <div class="row">
                      <div class="col-12">
                        <div class="float-left">
                          Total Tagihan
                        </div>
                        <div class="float-right" id="total-price-label">
                          Rp <%= (@transaction.price.to_i) %>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div style="margin-top: 30px">
                    <div class='cart'>
                      <!-- some other codes -->
                      <input type='hidden' name='snap-token' id='snap-token' value='<%=  %>'>
                      <%= hidden_field_tag 'snap_token', @snap_token %>
                      <a href='#' class='btn btn-success order-button disabled' style="width: 100%">Bayar</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
	</div>
</div>

<% content_for :customjs do %>
  <script type="text/javascript">
    $('#courier').select2({
      theme: "bootstrap4",
      placeholder: "Pilih kurir",
      allowClear: true
    });
    $('#duration').select2({
      theme: "bootstrap4",
      placeholder: "Pilih durasi",
      allowClear: true
    });
    $("#courier").val('').trigger('change');
    var user_id   = '<%= session[:user_id] %>';
    var transaction_id = '<%= (@transaction.id) %>';
    var trx_id    = '<%= (@transaction.trx_no) %>';
    var total_pay = '<%= (@transaction.price) %>';

    var couriers;
    var courier_type;
    var courier_service;
    var courier_etd;
    var courier_cost;

    $(function(){
      // On change courier
      $("#courier").change(function(){
        $('#duration').children('option').remove();
        courier_type = $(this).val().toUpperCase();
        generate_cost("501", "114", 1700, $(this).val());
        $('#pre-cost').html("");
        $('#delivery-cost-label').text('-');
        $('#total-price-label').text('Rp '+total_pay);
        $('.order-button').addClass('disabled');
      });
      // On change duration
      $("#duration").change(function(){
        $('#pre-cost').html("");
        $('#delivery-cost-label').text('-');
        $('#total-price-label').text('Rp '+total_pay);
        $('.order-button').addClass('disabled');
        var i   = $(this).val();
        var val = couriers.costs[i];
        if(val){
          courier_service = val.service
          courier_etd     = val.cost[0].etd
          courier_cost   = val.cost[0].value
          html = '<div>';
          html += '<span>'+courier_type+'</span>&nbsp;';
          html += '<span>'+courier_service+'</span>&nbsp;';
          html += '  <span>(Rp '+courier_cost+')</span>&emsp;';
          html += '</div>';
          html += '<div class="form-check">';
          html += '<label class="form-check-label">';
          html += '<input type="checkbox" class="form-check-input" value="">Asuransi Pengiriman';
          html += '</label>';
          html += '</div>';
          $('#pre-cost').html(html);
          var summary = parseInt(val.cost[0].value)+parseInt(total_pay);
          $('#delivery-cost-label').text(val.cost[0].value);
          $('#total-price-label').text('Rp '+summary);
          $('.order-button').removeClass('disabled');
        }
      });
    });

    function generate_cost(origin, destination, weight, courier){
      $.ajax({
          url: '<%= generate_cost_api_service_index_path %>',
          type: "POST",
          data: {
            origin      : origin,
            destination : destination,
            weight      : weight,
            courier     : courier
          },
          success: function (res) {
            $('#duration').children('option').remove();
            if(res.data){
              couriers = res.data[0];
              var i=0;
              couriers.costs.forEach(val => {
                html = '<option value="'+i+'">';
                html += val.cost[0].etd+' Hari ';
                html += '('+val.service+' - Rp '+val.cost[0].value+')';
                html += '</option>'
                $('#duration').append(html);
                i++;
              });
              $("#duration").val('').trigger('change');
            }
          }
      });
    }

    function finished_payment(code){
      $.ajax({
          url: '<%= payment_transaction_update_api_service_index_path %>',
          type: "POST",
          data: {
            user_id         : user_id,
            transaction_id  : transaction_id,
            courier_type    : courier_type,
            courier_service : courier_service,
            courier_etd     : courier_etd,
            courier_cost    : courier_cost,
            code            : code
          },
          success: function (res) {
            if(res.status=='200'){
              swal("Transaksi Berhasil!", "Terimakasih telah menyelesaikan tahap pembayaran, pesanan anda akan segera di proses.", "success")
              .then((value) => {
                window.location.href = "<%= transactions_path %>";
              });

            }else{
              swal("Transaksi Gagal!", "Mohon maaf terjadi kesalah, mohon hubungi pihak CS kami", "error");
            }
          }
      });
    }

    // Payment Midtrans
    var token = jQuery("#snap_token").val();

    $(".order-button").on("click", function() {
      $.ajax({
          url: '<%= generate_payment_token_api_service_index_path %>',
          type: "POST",
          data: {
            trx_id    : trx_id,
            total_pay : total_pay
          },
          success: function (res) {
            console.log();
            if(res.data.token){
              snap.pay(res.data.token, {
                onPending : function(res) {
                  console.log("PENDING RESPONSE", res);
                  finished_payment("02");
                },
                onSuccess : function(res) {
                  console.log("SUCCESS RESPONSE", res);
                  finished_payment("03");
                },
              });
            }
          }
      });
    });

    var end_date = '<%= @transaction.due_date.strftime("%Y-%m-%d %H:%M") %>';

    initializeClock('prefix_clock', 'clockdiv', end_date);

    function getTimeRemaining(endtime){
      var t = Date.parse(endtime) - Date.parse(new Date());
      var seconds = Math.floor( (t/1000) % 60 );
      var minutes = Math.floor( (t/1000/60) % 60 );
      var hours = Math.floor( (t/(1000*60*60)) % 24 );
      var days = Math.floor( t/(1000*60*60*24) );
      return {
        'total': t,
        'days': days,
        'hours': hours,
        'minutes': minutes,
        'seconds': seconds
      };
    }

    function initializeClock(prefix, id, end_date){
      var clock = document.getElementById(id);

      if(Date.parse(end_date) > Date.parse(new Date())){
        var timeinterval = setInterval(function(){
          var t = getTimeRemaining(endtime);
          clock.innerHTML = t.days + 'D : ' + t.hours + 'H : '+ t.minutes + 'M : ' + t.seconds +' S';
          if(t.total<=0){
            clearInterval(timeinterval);
            location.reload();
          }
        },1000);
      }else{
        $('#'+prefix).text('(Masa pembayaran telah berakhir)');
      }
    }
  </script>
<% end %>